OSL Script

val five = 19.216

val nagito = 1
val byakuya = 2

0x14|@{five, six, seven, eight}
0x00|1
0x01|1, 0b10
0x02|1, 0b10, 0o2
0x03|1, 0b10, 0o2, 3.0
0x04|1, 0b10, 0o2, 3.0, "4"
0x05|1, 0b10, 0o02, 3.0, "4", $five
0x06|1, 0b10, 0o02, 3.0, "4", $five, @{five, six, seven, eight}
0x07|1, 0b10, 0o02, 3.0, "4", $five, @{five, six, seven, eight}, %seven

0x02|"Hello, World!"
0x02|"This is a test"
Text|"&blue This is blue"