lexer grammar OSLBacktickLexer;
import LibLexer;

BACKTICK: BACKTICK_START (BACKTICKED_ESCAPES | BACKTICKED_STRING_CHARACTERS)* BACKTICK_END;
BACKTICK_START: '`' -> pushMode(DrillNameMode);

mode DrillNameMode;

BACKTICKED_ESCAPES: '\\' ('u' HEX_DIGITS HEX_DIGITS HEX_DIGITS HEX_DIGITS | BACKTICKED_ESCAPE_CHARACTERS);
BACKTICKED_STRING_CHARACTERS: ~[`\\]+;

fragment BACKTICKED_ESCAPE_CHARACTERS: ["\\/bfnrt];

BACKTICK_END: '`' -> popMode;